%% ========================================================================
%  Hybrid SMF-DCF-EDFA Optical Link Simulation  (CORRECTED / FINAL)
%  Split-Step Fourier Method (SSFM) solving the Nonlinear Schrodinger Equation
%
%  Architecture:
%  Tx -> SMF(100km) -> DCF(17km) -> EDFA -> SMF(100km) -> DCF(17km) -> EDFA -> Rx
%
%  This script produces REAL simulation output. No results are assumed or
%  pre-written; every number is generated by running this code.
%
%  Corrections applied in this version (vs. first draft):
%   1. Added explicit single-pulse dispersion/compensation visualization
%      (input pulse vs. SMF-only output vs. SMF+DCF+EDFA output).
%   2. BER computed from the extracted Q-factor is explicitly labeled
%      "Q-estimated BER" throughout (NOT a bit-count/Monte-Carlo BER).
%   3. EDFA ASE noise is now bandwidth-limited by an explicit optical
%      bandpass filter (4x bit rate, super-Gaussian) placed after each
%      EDFA, so ASE is not loaded across the full simulation sampling
%      bandwidth. This avoids an artificially inflated noise floor.
%   4. Pulse generation now uses an ideal rectangular NRZ sequence passed
%      through an explicitly-defined Gaussian transmitter low-pass filter
%      (0.75 x bit rate, 3-dB bandwidth) instead of manual ad-hoc windowing.
%   5. Added an explicit 0.5 dB interconnection/splice loss per span
%      (between DCF and EDFA), so the simulated span loss (20+8.5+0.5=29 dB)
%      exactly matches the analytical span-loss budget used in Section 5.
%      Previously the simulation implicitly used 28.5 dB (SMF+DCF only).
%   6. Visualization-only fixes (no change to underlying results):
%      - Pulse-shape figure now shows each trace independently normalized
%        to its own peak (isolating temporal shape/dispersion from
%        attenuation), plus a separate absolute-power panel.
%      - Eye diagrams are now normalized to a common 0-1 scale so the two
%        cases can be compared on eye opening/distortion rather than on
%        absolute amplifier gain. Absolute received power is unaffected
%        and remains reported separately in the console summary table.
%   7. FIGURE SIZING FIX: each figure() call now sets an explicit
%      'Position' (width/height in pixels) sized generously for its
%      title/subplot-title content, so titles and sgtitles no longer
%      overlap or get clipped when saved via exportgraphics. Previously
%      figures used MATLAB's default size, which was too narrow for the
%      4-panel sweep figure's subplot titles and too short for the
%      sgtitle clearance above the eye-diagram / pulse-propagation
%      subplot titles.
%
%  NOTE: This is a numerical SSFM model of the physical system, not a
%  claim of exact equivalence to OptiSystem/VPIphotonics. Modeling
%  assumptions and limitations are stated in the accompanying report.
%
%  MATLAB compatibility: written/tested for R2021a. Base MATLAB only
%  (no toolbox-specific functions used).
% ========================================================================

clear; close all; clc;

%% ---------------- Frozen Parameter Set (UNCHANGED) ----------------------
Rb          = 10e9;            % Data rate, bits/s (10 Gbps)
lambda      = 1550e-9;         % Operating wavelength, m
c           = 3e8;             % Speed of light, m/s

alpha_SMF_dBkm   = 0.20;       % dB/km
gamma_SMF_perWkm = 1.3;        % 1/(W*km)
L_SMF_km         = 100;        % km

alpha_DCF_dBkm   = 0.50;       % dB/km
gamma_DCF_perWkm = 5.06;       % 1/(W*km)
L_DCF_km         = 17;         % km

D_SMF_ps = 17;                 % ps/(nm.km)
D_DCF_ps = -100;                % ps/(nm.km)

G_EDFA_dB = 29;                 % operating gain, dB
NF_dB     = 5;                  % noise figure, dB
interconnLoss_dB = 0.5;         % splice/connector interconnection loss per span, dB
                                 % (matches analytical span budget: 20+8.5+0.5=29 dB)
h         = 6.626e-34;          % Planck constant, J.s
nu        = c/lambda;           % optical frequency, Hz

Nspans        = 2;
P0_dBm_default = 0;

% --- New, explicitly stated filter parameters (corrections 3 & 4) -------
Tx_LPF_BW   = 0.75*Rb;          % transmitter Gaussian LPF, 3-dB bandwidth (Hz)
OBPF_BW     = 4*Rb;             % optical bandpass filter after EDFA, 3-dB bandwidth (Hz)
OBPF_order  = 2;                % super-Gaussian order (2 = mildly flat-top)

fprintf('=== Hybrid SMF-DCF-EDFA Link Simulation (SSFM) - Corrected Version ===\n');
fprintf('Data rate: %.0f Gbps | Wavelength: %.0f nm\n', Rb/1e9, lambda*1e9);
fprintf('Tx LPF BW = %.1f GHz | Optical BPF BW = %.1f GHz\n', Tx_LPF_BW/1e9, OBPF_BW/1e9);

%% ---------------- Convert units to SI -----------------------------------
L_SMF = L_SMF_km*1e3;
L_DCF = L_DCF_km*1e3;

gamma_SMF = gamma_SMF_perWkm/1e3;
gamma_DCF = gamma_DCF_perWkm/1e3;

D_SMF_SI = D_SMF_ps*1e-12/(1e-9*1e3);
D_DCF_SI = D_DCF_ps*1e-12/(1e-9*1e3);

beta2_SMF = -(lambda^2/(2*pi*c)) * D_SMF_SI;
beta2_DCF = -(lambda^2/(2*pi*c)) * D_DCF_SI;

alpha_SMF = alpha_SMF_dBkm/(4.343*1e3);
alpha_DCF = alpha_DCF_dBkm/(4.343*1e3);

%% ---------------- Time / frequency grid ----------------------------------
Nbits = 128;
Nsps  = 32;
Tb    = 1/Rb;
Nt    = Nbits*Nsps;
dt    = Tb/Nsps;
t     = (0:Nt-1)*dt;
Fs    = 1/dt;
f     = (-Nt/2:Nt/2-1)*(Fs/Nt);
omega = 2*pi*f;

%% ---------------- Correction 4: clean NRZ pulse generation ---------------
rng(1);
bits = randi([0 1], 1, Nbits);

% Ideal rectangular NRZ (amplitude 1 for '1' bits, 0 for '0' bits)
ideal_nrz = zeros(1, Nt);
for k = 1:Nbits
    idx = (k-1)*Nsps + (1:Nsps);
    if bits(k) == 1
        ideal_nrz(idx) = 1;
    end
end

% Pass through explicitly-defined Gaussian transmitter LPF (0.75*Rb, 3-dB BW)
pulse_shape = gaussian_lpf(ideal_nrz, f, Tx_LPF_BW);
pulse_shape = pulse_shape / max(abs(pulse_shape));   % normalize peak to 1

%% ---------------- Package shared parameters -------------------------------
params.dt = dt; params.omega = omega; params.t = t; params.f = f;
params.Nsps = Nsps; params.Nbits = Nbits; params.bits = bits;
params.pulse_shape = pulse_shape;
params.alpha_SMF = alpha_SMF; params.beta2_SMF = beta2_SMF; params.gamma_SMF = gamma_SMF; params.L_SMF = L_SMF;
params.alpha_DCF = alpha_DCF; params.beta2_DCF = beta2_DCF; params.gamma_DCF = gamma_DCF; params.L_DCF = L_DCF;
params.G_EDFA_dB = G_EDFA_dB; params.NF_dB = NF_dB; params.h = h; params.nu = nu;
params.Nspans = Nspans;
params.OBPF_BW = OBPF_BW; params.OBPF_order = OBPF_order;
params.interconnLoss_dB = interconnLoss_dB;

%% ============== CASE 1: SMF-only baseline (no DCF/EDFA) ===================
res1 = run_case('Case 1: SMF-only baseline', false, P0_dBm_default, params, true);

%% ============== CASE 2: Full SMF+DCF+EDFA system ===========================
res2 = run_case('Case 2: SMF+DCF+EDFA', true, P0_dBm_default, params, true);

%% ============== CASE 3: Launch-power sweep (full system) ===================
sweepPowers_dBm = -4:2:8;
Q_sweep    = zeros(size(sweepPowers_dBm));
BERQ_sweep = zeros(size(sweepPowers_dBm));
RxP_sweep  = zeros(size(sweepPowers_dBm));
PhiNL_analytical = zeros(size(sweepPowers_dBm));

fprintf('\n--- Running Case 3: Launch-power sweep ---\n');
for i = 1:length(sweepPowers_dBm)
    r = run_case(sprintf('Sweep P0=%d dBm', sweepPowers_dBm(i)), true, sweepPowers_dBm(i), params, true);
    Q_sweep(i)    = r.Q;
    BERQ_sweep(i) = r.BERQ;
    RxP_sweep(i)  = r.avgRxPower_dBm;

    % Analytical Phi_NL for direct comparison with Section 5 hand-calculation
    P0_W = 1e-3*10^(sweepPowers_dBm(i)/10);
    Leff_SMF = (1-exp(-alpha_SMF*L_SMF))/alpha_SMF;
    Leff_DCF = (1-exp(-alpha_DCF*L_DCF))/alpha_DCF;
    P_into_DCF = P0_W*exp(-alpha_SMF*L_SMF);
    phi_perSpan = gamma_SMF*P0_W*Leff_SMF + gamma_DCF*P_into_DCF*Leff_DCF;
    PhiNL_analytical(i) = Nspans*phi_perSpan;
end

%% ============== Correction 1: Single-pulse dispersion/compensation demo ===
fprintf('\n--- Running single-pulse dispersion visualization (no ASE) ---\n');
Nbits_test = 16;
bits_test = zeros(1, Nbits_test); bits_test(round(Nbits_test/2)) = 1;   % one isolated '1'
Nt_test = Nbits_test*Nsps;
t_test  = (0:Nt_test-1)*dt;
f_test  = (-Nt_test/2:Nt_test/2-1)*(Fs/Nt_test);
omega_test = 2*pi*f_test;

ideal_test = zeros(1, Nt_test);
idxOne = (round(Nbits_test/2)-1)*Nsps + (1:Nsps);
ideal_test(idxOne) = 1;
test_pulse = gaussian_lpf(ideal_test, f_test, Tx_LPF_BW);
test_pulse = test_pulse/max(abs(test_pulse));

P0_test = 1e-3*10^(P0_dBm_default/10);
E0_test = sqrt(P0_test)*test_pulse;

dz = 1e3;
% (a) SMF-only, 2 spans, no DCF/EDFA
A_smf = E0_test;
for s = 1:Nspans
    A_smf = ssfm_propagate(A_smf, omega_test, alpha_SMF, beta2_SMF, gamma_SMF, L_SMF, dz);
end

% (b) Full system, 2 spans, EDFA gain applied WITHOUT noise (deterministic,
%     to isolate the dispersion/nonlinearity/compensation effect on pulse shape)
A_full = E0_test;
for s = 1:Nspans
    A_full = ssfm_propagate(A_full, omega_test, alpha_SMF, beta2_SMF, gamma_SMF, L_SMF, dz);
    A_full = ssfm_propagate(A_full, omega_test, alpha_DCF, beta2_DCF, gamma_DCF, L_DCF, dz);
    A_full = A_full * 10^(-interconnLoss_dB/20);   % explicit 0.5 dB interconnection loss
    A_full = edfa_amplify(A_full, G_EDFA_dB, NF_dB, h, nu, dt, false);  % noise OFF
    A_full = optical_bpf(A_full, f_test, OBPF_BW, OBPF_order);
end

% --- FIX: explicit Position [x y width height] sized to give the sgtitle
%     clearance above the two subplot titles (previous default size
%     caused the sgtitle to overlap the "Pulse Shape.../Absolute Power..."
%     subplot titles beneath it). ---
figure('Name','Pulse Shape: Dispersion and Compensation', 'Position',[50 50 1600 650]);

% --- Panel 1: each trace independently normalized to its own peak ---
% This isolates TEMPORAL SHAPE (broadening/compensation) from absolute
% power loss, which is shown separately in Panel 2.
subplot(1,2,1);
Pin  = abs(E0_test).^2;
Psmf = abs(A_smf).^2;
Pfull= abs(A_full).^2;
plot(t_test*1e9, Pin/max(Pin), 'k-', 'LineWidth', 1.5); hold on;
plot(t_test*1e9, Psmf/max(Psmf), 'r--', 'LineWidth', 1.5);
plot(t_test*1e9, Pfull/max(Pfull), 'b-', 'LineWidth', 1.5);
legend('Input pulse', 'After SMF-only (2 spans)', 'After SMF+DCF+EDFA (2 spans)', 'Location','best');
xlabel('Time (ns)'); ylabel('Power normalized to own peak');
title('Pulse Shape (each trace independently normalized)');
grid on;

% --- Panel 2: absolute power (shows attenuation, not shape) ---
subplot(1,2,2);
plot(t_test*1e9, Pin, 'k-', 'LineWidth', 1.5); hold on;
plot(t_test*1e9, Psmf, 'r--', 'LineWidth', 1.5);
plot(t_test*1e9, Pfull, 'b-', 'LineWidth', 1.5);
legend('Input pulse', 'After SMF-only (2 spans)', 'After SMF+DCF+EDFA (2 spans)', 'Location','best');
xlabel('Time (ns)'); ylabel('Absolute Power (W)');
title('Absolute Power (shows attenuation, not shape)');
grid on;

sgtitle('Single-Pulse Propagation: Shape (left) vs. Absolute Power (right)');


%% ============== DIAGNOSTIC: Noise-limited vs Nonlinearity-limited check ====
%  Control experiment (does not alter any frozen parameter or the official
%  -4 to +8 dBm sweep results above). Answers: is the monotonic Q-rise in
%  Case 3 genuinely noise/SNR-limited, or is nonlinearity under-represented?

fprintf('\n\n=== DIAGNOSTIC: Linear vs Nonlinear at +8 dBm (same noise seed) ===\n');

P0_test_dBm = 8;

rng(42);
res_NL = run_case('Diagnostic: +8dBm WITH nonlinearity', true, P0_test_dBm, params, true);

params_lin = params;
params_lin.gamma_SMF = 0;
params_lin.gamma_DCF = 0;

rng(42);
res_LIN = run_case('Diagnostic: +8dBm WITHOUT nonlinearity (gamma=0)', true, P0_test_dBm, params_lin, true);

fprintf('\n--- Diagnostic Result ---\n');
fprintf('WITH nonlinearity:    Q = %.3f | Q-est.BER = %.3e\n', res_NL.Q, res_NL.BERQ);
fprintf('WITHOUT nonlinearity: Q = %.3f | Q-est.BER = %.3e\n', res_LIN.Q, res_LIN.BERQ);
fprintf('Delta Q due to nonlinearity alone = %.3f\n', res_LIN.Q - res_NL.Q);

if abs(res_LIN.Q - res_NL.Q) < 0.3
    fprintf(['\nInterpretation: Nonlinearity has NEGLIGIBLE effect on Q at +8 dBm.\n' ...
             'The rising Q with launch power is genuinely a noise/SNR-limited effect,\n' ...
             'not an artifact of insufficient nonlinear modeling.\n']);
else
    fprintf(['\nInterpretation: Nonlinearity IS measurably reducing Q at +8 dBm,\n' ...
             'but the SNR improvement from higher launch power still outweighs it\n' ...
             'in this power range and span count.\n']);
end

%% --- Supplementary (diagnostic only): extended power range to find turnover
fprintf('\n=== DIAGNOSTIC: Extended power range (diagnostic only, not official result) ===\n');
extendedPowers_dBm = [8 10 12 14 16 18 20];
Q_ext = zeros(size(extendedPowers_dBm));
for i = 1:length(extendedPowers_dBm)
    rng(1);
    r = run_case(sprintf('Extended P0=%d dBm', extendedPowers_dBm(i)), true, extendedPowers_dBm(i), params, true);
    Q_ext(i) = r.Q;
end

% --- FIX: explicit Position (default size was fine here, but set for
%     consistency and to guarantee the title text has room) ---
figure('Name','Diagnostic: Extended Power Range', 'Position',[50 50 1000 600]);
plot([sweepPowers_dBm, extendedPowers_dBm(2:end)], [Q_sweep, Q_ext(2:end)], '-o');
xlabel('Launch Power (dBm)'); ylabel('Q-factor');
title('Diagnostic: Q-factor over Extended Power Range (looking for turnover)');
grid on;

fprintf('\nCheck the plotted figure: does Q eventually turn over and decrease\n');
fprintf('at higher power? If yes, this confirms nonlinear penalty exists in the\n');
fprintf('model and simply requires higher power than +8 dBm to dominate, which\n');
fprintf('is physically reasonable for a 2-span, dispersion-compensated link.\n');

%% ---------------- PLOTS: Eye diagrams and sweep results --------------------

% --- FIX: explicit Position sized taller so the sgtitle (which is long)
%     has clearance above the two subplot titles beneath it. Previously
%     the default figure height caused the sgtitle to overlap
%     "Case 1: SMF-only Eye Diagram" / "Case 2: SMF+DCF+EDFA Eye Diagram". ---
figure('Name','Eye Diagrams', 'Position',[50 50 1400 750]);
subplot(1,2,1);
plot(res1.eyeMatrix/max(res1.eyeMatrix(:)), 'b'); title('Case 1: SMF-only Eye Diagram');
xlabel('Sample within bit period'); ylabel('Power (normalized to own peak)'); ylim([0 1.05]); grid on;

subplot(1,2,2);
plot(res2.eyeMatrix/max(res2.eyeMatrix(:)), 'r'); title('Case 2: SMF+DCF+EDFA Eye Diagram');
xlabel('Sample within bit period'); ylabel('Power (normalized to own peak)'); ylim([0 1.05]); grid on;

sgtitle('Eye Diagrams (each normalized to its own peak for shape comparison; see Results table for absolute received power)');

% --- FIX: explicit Position, much WIDER than the previous default, so
%     the 4 subplot titles ("Q-factor vs Launch Power", "Q-estimated BER
%     vs Launch Power", etc.) each have room and no longer run into the
%     adjacent subplot's title. ---
figure('Name','Launch Power Sweep Results', 'Position',[50 50 1900 500]);
subplot(1,4,1);
plot(sweepPowers_dBm, Q_sweep, '-o'); grid on;
xlabel('Launch Power (dBm)'); ylabel('Q-factor'); title('Q-factor vs Launch Power');

subplot(1,4,2);
semilogy(sweepPowers_dBm, BERQ_sweep, '-s'); grid on;
xlabel('Launch Power (dBm)'); ylabel('Q-estimated BER'); title('Q-estimated BER vs Launch Power');

subplot(1,4,3);
plot(sweepPowers_dBm, RxP_sweep, '-^'); grid on;
xlabel('Launch Power (dBm)'); ylabel('Avg Received Power (dBm)'); title('Received Power vs Launch Power');

subplot(1,4,4);
plot(sweepPowers_dBm, PhiNL_analytical, '-d'); grid on;
xlabel('Launch Power (dBm)'); ylabel('\Phi_{NL} (rad, analytical)'); title('Analytical Nonlinear Phase vs Power');

%% ---------------- Summary ---------------------------------------------------
fprintf('\n=== SUMMARY ===\n');
fprintf('Case 1 (SMF-only):      Q=%.3f, Q-estimated BER=%.3e, RxP=%.2f dBm\n', res1.Q, res1.BERQ, res1.avgRxPower_dBm);
fprintf('Case 2 (SMF+DCF+EDFA):  Q=%.3f, Q-estimated BER=%.3e, RxP=%.2f dBm\n', res2.Q, res2.BERQ, res2.avgRxPower_dBm);
fprintf('\nCase 3 (Power Sweep) - Analytical vs Simulated:\n');
fprintf('P0(dBm)\tQ\tQ-est.BER\tRxPower(dBm)\tPhiNL_analytical(rad)\n');
for i = 1:length(sweepPowers_dBm)
    fprintf('%d\t%.3f\t%.3e\t%.2f\t\t%.5f\n', sweepPowers_dBm(i), Q_sweep(i), BERQ_sweep(i), RxP_sweep(i), PhiNL_analytical(i));
end

fprintf('\nNOTE: "Q-estimated BER" is derived from the extracted Q-factor via\n');
fprintf('BER = 0.5*erfc(Q/sqrt(2)). It is NOT a bit-count/Monte-Carlo BER.\n');
fprintf('Use the printed values and generated figures directly in Section 7.\n');

%% Save Final Report Figures

figFolder = fullfile(pwd, 'Report_Figures');

if ~exist(figFolder, 'dir')
    mkdir(figFolder);
end

% Save all currently open figures
figHandles = findall(0, 'Type', 'figure');

for k = 1:length(figHandles)
    figure(figHandles(k));
    exportgraphics(figHandles(k), ...
        fullfile(figFolder, sprintf('Figure_%d.png', k)), ...
        'Resolution', 300);
end

disp('All figures saved in the Report_Figures folder.');
%% ========================================================================
%  LOCAL FUNCTIONS (must appear at the end of a MATLAB script file)
% ========================================================================

function y = gaussian_lpf(x, f, BW3dB)
    % Explicit Gaussian low-pass filter (transmitter response), base MATLAB only.
    % BW3dB: 3-dB (power) one-sided bandwidth, Hz.
    sigma = BW3dB/sqrt(log(2));
    H = exp(-0.5*(f/sigma).^2);
    X = fftshift(fft(x));
    Y = X.*H;
    y = ifft(ifftshift(Y));
end

function y = optical_bpf(x, f, BW3dB, order)
    % Super-Gaussian optical bandpass filter applied to the field spectrum.
    % BW3dB: full 3-dB bandwidth, Hz. order: super-Gaussian order (1=Gaussian).
    H = exp(-0.5*log(2)*(2*f/BW3dB).^(2*order));
    X = fftshift(fft(x));
    Y = X.*H;
    y = ifft(ifftshift(Y));
end

function Aout = ssfm_propagate(Ain, omega, alpha, beta2, gamma, L, dz)
    % Symmetric split-step Fourier method for one fiber segment.
    Nsteps = max(1, round(L/dz));
    A = Ain;
    linOperator = exp((-alpha/2 + 1i*(beta2/2).*(omega.^2)) * (dz/2));
    for n = 1:Nsteps
        A = ifft(ifftshift(fftshift(fft(A)).*linOperator));
        A = A .* exp(1i*gamma*abs(A).^2*dz);
        A = ifft(ifftshift(fftshift(fft(A)).*linOperator));
    end
    Aout = A;
end

function Aout = edfa_amplify(Ain, G_dB, NF_dB, h, nu, dt, addNoise)
    % EDFA: power-domain gain plus bandwidth-referenced ASE noise.
    % addNoise = false disables noise injection (used for the deterministic
    % single-pulse dispersion/compensation visualization).
    if nargin < 7
        addNoise = true;
    end
    G_lin = 10^(G_dB/10);
    Aout = sqrt(G_lin)*Ain;
    if addNoise
        NF_lin = 10^(NF_dB/10);
        S_ASE = (G_lin - 1) * NF_lin * h * nu / 2;   % W/Hz, one-sided approx
        N = length(Ain);
        Fs_local = 1/dt;
        noise_power = S_ASE * Fs_local;
        noise_std = sqrt(noise_power/2);
        noise = noise_std*(randn(1,N) + 1i*randn(1,N));
        Aout = Aout + noise;
    end
end

function results = run_case(caseName, includeDCF_EDFA, P0_dBm, params, addNoise)
    fprintf('\n--- Running %s (P0 = %.1f dBm) ---\n', caseName, P0_dBm);

    P0 = 1e-3 * 10^(P0_dBm/10);
    E0 = sqrt(P0) * params.pulse_shape;

    dz = 1e3;
    A = E0;
    for span = 1:params.Nspans
        A = ssfm_propagate(A, params.omega, params.alpha_SMF, params.beta2_SMF, params.gamma_SMF, params.L_SMF, dz);

        if includeDCF_EDFA
            A = ssfm_propagate(A, params.omega, params.alpha_DCF, params.beta2_DCF, params.gamma_DCF, params.L_DCF, dz);
            % Explicit splice/connector interconnection loss (0.5 dB per span),
            % matching the analytical span-loss budget: 20 + 8.5 + 0.5 = 29 dB.
            A = A * 10^(-params.interconnLoss_dB/20);   % field amplitude scaling (dB/20, not dB/10, since loss is on power)
            A = edfa_amplify(A, params.G_EDFA_dB, params.NF_dB, params.h, params.nu, params.dt, addNoise);
            A = optical_bpf(A, params.f, params.OBPF_BW, params.OBPF_order);
        end
    end

    Prx = abs(A).^2;

    Nsps = params.Nsps; Nbits = params.Nbits;
    eyeMatrix = reshape(Prx(1:Nsps*Nbits), Nsps, Nbits);

    centerIdx = round(Nsps/2);
    samples_at_center = eyeMatrix(centerIdx, :);
    bits = params.bits;
    ones_samples = samples_at_center(bits==1);
    zeros_samples = samples_at_center(bits==0);

    mu1 = mean(ones_samples); sigma1 = std(ones_samples);
    mu0 = mean(zeros_samples); sigma0 = std(zeros_samples);

    Q = (mu1 - mu0) / (sigma1 + sigma0 + eps);
    BERQ = 0.5*erfc(Q/sqrt(2));   % Q-estimated BER (not bit-count BER)

    avgRxPower_dBm = 10*log10(mean(Prx)/1e-3 + eps);

    fprintf('Q-factor = %.3f | Q-estimated BER = %.3e | Avg Rx Power = %.2f dBm\n', Q, BERQ, avgRxPower_dBm);

    results.eyeMatrix = eyeMatrix;
    results.Q = Q;
    results.BERQ = BERQ;
    results.avgRxPower_dBm = avgRxPower_dBm;
    results.Prx = Prx;
end